/**
 * Computes the real content counts and writes them to
 * src/data/stats.generated.ts.
 *
 * Two reasons this exists rather than counting in a component:
 *  - the homepage can show real totals without importing the whole question
 *    bank, which keeps ~320 kB of content out of the first load;
 *  - it fails the build on content that would render as a broken page: an
 *    unanswerable multiple-choice question, a roadmap level pointing at a
 *    topic that does not exist, an unreachable topic, a dangling prerequisite.
 *
 * Runs automatically via the prebuild script.
 */
import { rolldown } from "rolldown";
import { writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const bundle = await rolldown({
  input: "src/data/index-stats.ts",
  platform: "node",
  logLevel: "silent",
});
const { output } = await bundle.generate({ format: "esm" });

const entry = join(mkdtempSync(join(tmpdir(), "bb-stats-")), "entry.mjs");
writeFileSync(entry, output[0].code);
const { stats, problems, notes } = await import(`file://${entry}`);

if (problems.length) {
  console.error(`Content integrity: ${problems.length} problem(s)`);
  for (const line of problems) console.error(`  - ${line}`);
  process.exit(1);
}

const lines = Object.entries(stats)
  .map(([key, value]) => `  ${key}: ${value},`)
  .join("\n");

writeFileSync(
  "src/data/stats.generated.ts",
  `// Generated by scripts/content-stats.mjs — do not edit by hand.\n` +
    `// Run \`npm run stats\` (or any build) to refresh.\n` +
    `export const stats = {\n${lines}\n} as const;\n`,
);

for (const line of notes) console.log(`note: ${line}`);
console.log("content stats:", stats);
