// Generated by scripts/content-stats.mjs — do not edit by hand.
// A link-level index of the curriculum, without lesson bodies, so pages
// that only need titles do not download the whole corpus.
import type { CatalogLevel, CatalogTopic } from "./catalogTypes";

export const catalogTopics: CatalogTopic[] = [
  {
    "slug": "what-is-linux",
    "title": "What is Linux?",
    "summary": "Linux is a kernel, and a Linux system is that kernel plus userland tools, libraries, and a package-managed distribution.",
    "difficulty": "Beginner",
    "minutes": 30,
    "level": 0,
    "concepts": 5
  },
  {
    "slug": "linux-vs-unix",
    "title": "Linux vs Unix",
    "summary": "Unix is a family of operating systems and a design culture. Linux is a Unix-like kernel that is not derived from AT&T Unix source.",
    "difficulty": "Beginner",
    "minutes": 28,
    "level": 0,
    "concepts": 3
  },
  {
    "slug": "distributions",
    "title": "Linux distributions",
    "summary": "Pick a distro family and you pick a package format, release model, and default administration style.",
    "difficulty": "Beginner",
    "minutes": 26,
    "level": 0,
    "concepts": 3
  },
  {
    "slug": "kernel-and-gnu",
    "title": "Kernel, GNU, and open source",
    "summary": "A typical Linux system is GNU userland plus the Linux kernel, licensed as free and open source software.",
    "difficulty": "Beginner",
    "minutes": 27,
    "level": 0,
    "concepts": 3
  },
  {
    "slug": "architecture",
    "title": "Linux architecture",
    "summary": "Applications talk to the kernel through system calls. The kernel talks to hardware. The shell is just another user program.",
    "difficulty": "Beginner",
    "minutes": 32,
    "level": 0,
    "concepts": 3
  },
  {
    "slug": "boot-and-init",
    "title": "Boot process and init",
    "summary": "Firmware loads a bootloader, the bootloader loads the kernel, the kernel starts PID 1 (usually systemd).",
    "difficulty": "Intermediate",
    "minutes": 34,
    "level": 0,
    "concepts": 3
  },
  {
    "slug": "directory-map",
    "title": "Directory structure (FHS)",
    "summary": "Linux paths are a contract: /etc is config, /var is variable data, /usr is shipped software, /home is people.",
    "difficulty": "Beginner",
    "minutes": 32,
    "level": 0,
    "concepts": 3
  },
  {
    "slug": "help-systems",
    "title": "man, info, and --help",
    "summary": "The local system documents itself. Learn the sections and you become independent.",
    "difficulty": "Beginner",
    "minutes": 24,
    "level": 0,
    "concepts": 3
  },
  {
    "slug": "terminal-shell",
    "title": "Terminal, console, and shell",
    "summary": "The terminal displays bytes. The shell interprets your typing. They are not the same program.",
    "difficulty": "Beginner",
    "minutes": 28,
    "level": 1,
    "concepts": 3
  },
  {
    "slug": "bash-basics",
    "title": "Bash commands, arguments, and the prompt",
    "summary": "A command line is a program name plus arguments. The prompt is a hint, not part of the command.",
    "difficulty": "Beginner",
    "minutes": 30,
    "level": 1,
    "concepts": 3
  },
  {
    "slug": "env-and-path",
    "title": "Environment variables and PATH",
    "summary": "Child processes inherit environment variables. PATH is the list of directories searched for commands.",
    "difficulty": "Beginner",
    "minutes": 28,
    "level": 1,
    "concepts": 3
  },
  {
    "slug": "quoting-expansion",
    "title": "Quoting, escaping, and expansion",
    "summary": "The shell rewrites your line before the program sees it: globs, variables, command substitution, word splitting.",
    "difficulty": "Beginner",
    "minutes": 32,
    "level": 1,
    "concepts": 3
  },
  {
    "slug": "inodes-and-links",
    "title": "Inodes, hard links, and symbolic links",
    "summary": "A filename is a directory entry pointing at an inode. Hard links are extra names. Symlinks are path strings.",
    "difficulty": "Intermediate",
    "minutes": 32,
    "level": 2,
    "concepts": 3
  },
  {
    "slug": "mounts",
    "title": "Mounts and mount points",
    "summary": "A filesystem is usable only after it is mounted on a directory.",
    "difficulty": "Intermediate",
    "minutes": 28,
    "level": 2,
    "concepts": 3
  },
  {
    "slug": "fhs-deep-dive",
    "title": "Important directories in depth",
    "summary": "/etc configuration, /var state, /usr shipped software, /proc and /sys kernel interfaces, /dev devices, /run runtime.",
    "difficulty": "Beginner",
    "minutes": 30,
    "level": 2,
    "concepts": 3
  },
  {
    "slug": "users-groups",
    "title": "Users, groups, root, and sudo",
    "summary": "Identity is a UID and GIDs. Root is UID 0. sudo is controlled delegation.",
    "difficulty": "Beginner",
    "minutes": 30,
    "level": 3,
    "concepts": 3
  },
  {
    "slug": "mode-bits",
    "title": "Permission bits, chmod, chown, umask",
    "summary": "Each file has owner, group, and a mode: rwx for user, group, others.",
    "difficulty": "Beginner",
    "minutes": 34,
    "level": 3,
    "concepts": 3
  },
  {
    "slug": "special-bits-acl",
    "title": "setuid, setgid, sticky bit, and ACLs",
    "summary": "Special mode bits change execution identity or deletion rules. ACLs add named users beyond owner/group/other.",
    "difficulty": "Intermediate",
    "minutes": 30,
    "level": 3,
    "concepts": 3
  },
  {
    "slug": "process-model",
    "title": "What is a process?",
    "summary": "A process is a running program with a PID, memory, file descriptors, and credentials.",
    "difficulty": "Beginner",
    "minutes": 32,
    "level": 4,
    "concepts": 3
  },
  {
    "slug": "jobs-signals",
    "title": "Jobs, foreground, background, signals",
    "summary": "Job control is a shell feature. Signals are kernel messages to processes.",
    "difficulty": "Intermediate",
    "minutes": 30,
    "level": 4,
    "concepts": 3
  },
  {
    "slug": "process-control",
    "title": "Monitoring and controlling processes",
    "summary": "ps, top, nice, and zombie/orphan behavior.",
    "difficulty": "Intermediate",
    "minutes": 28,
    "level": 4,
    "concepts": 3
  },
  {
    "slug": "net-fundamentals",
    "title": "IP, TCP, UDP, and ports",
    "summary": "Hosts have addresses. Processes bind ports. TCP is a connection; UDP is datagrams.",
    "difficulty": "Beginner",
    "minutes": 34,
    "level": 5,
    "concepts": 3
  },
  {
    "slug": "name-resolution",
    "title": "DNS, DHCP, and routing basics",
    "summary": "DHCP configures an address. DNS maps names. Routing decides the next hop.",
    "difficulty": "Intermediate",
    "minutes": 30,
    "level": 5,
    "concepts": 3
  },
  {
    "slug": "remote-access",
    "title": "SSH and copying files",
    "summary": "SSH is the standard encrypted admin channel. Keys beat passwords.",
    "difficulty": "Beginner",
    "minutes": 28,
    "level": 5,
    "concepts": 3
  },
  {
    "slug": "package-managers",
    "title": "Package management",
    "summary": "Packages are signed bundles with metadata and dependencies, served from repositories.",
    "difficulty": "Beginner",
    "minutes": 30,
    "level": 6,
    "concepts": 3
  },
  {
    "slug": "bash-scripting",
    "title": "Bash scripting fundamentals",
    "summary": "Variables, tests, loops, functions, exit codes, and set -euo pipefail with its caveats.",
    "difficulty": "Intermediate",
    "minutes": 36,
    "level": 7,
    "concepts": 3
  },
  {
    "slug": "pipes-redirection",
    "title": "Pipes, redirection, and descriptors",
    "summary": "stdin 0, stdout 1, stderr 2. Pipes connect stdout of one process to stdin of the next.",
    "difficulty": "Beginner",
    "minutes": 30,
    "level": 7,
    "concepts": 3
  },
  {
    "slug": "practical-scripts",
    "title": "Practical Bash scripts",
    "summary": "Backup, log grep, disk check, service check, file organizer — patterns you can adapt.",
    "difficulty": "Intermediate",
    "minutes": 32,
    "level": 7,
    "concepts": 3
  },
  {
    "slug": "systemd",
    "title": "systemd units and services",
    "summary": "Units describe services, sockets, mounts, timers. systemctl is the control plane.",
    "difficulty": "Intermediate",
    "minutes": 34,
    "level": 8,
    "concepts": 3
  },
  {
    "slug": "logs-and-jobs",
    "title": "Logs, cron, and timers",
    "summary": "journald is the systemd log. cron and systemd timers schedule work.",
    "difficulty": "Intermediate",
    "minutes": 28,
    "level": 8,
    "concepts": 3
  },
  {
    "slug": "host-config",
    "title": "Hostname, time, locale, SSH server",
    "summary": "Identity of a machine: name, clock, language, and how admins log in.",
    "difficulty": "Beginner",
    "minutes": 26,
    "level": 8,
    "concepts": 3
  },
  {
    "slug": "disks-partitions",
    "title": "Disks, partitions, and filesystem types",
    "summary": "Block devices are split into partitions with a table (GPT or MBR) and formatted with a filesystem.",
    "difficulty": "Advanced",
    "minutes": 32,
    "level": 9,
    "concepts": 3
  },
  {
    "slug": "lvm-and-fstab",
    "title": "LVM, fstab, df, and du",
    "summary": "LVM abstracts disks into flexible volumes. fstab mounts them at boot. df vs du diagnose fullness.",
    "difficulty": "Advanced",
    "minutes": 30,
    "level": 9,
    "concepts": 3
  },
  {
    "slug": "linux-security",
    "title": "Linux security model",
    "summary": "Discretionary permissions, sudo, SSH, MAC (SELinux/AppArmor), firewalls, and least privilege.",
    "difficulty": "Advanced",
    "minutes": 34,
    "level": 10,
    "concepts": 3
  },
  {
    "slug": "performance-basics",
    "title": "Performance and monitoring",
    "summary": "Measure CPU, memory, disk, network before changing anything. Load average is a queue length.",
    "difficulty": "Advanced",
    "minutes": 32,
    "level": 11,
    "concepts": 3
  },
  {
    "slug": "tcp-and-sockets",
    "title": "TCP internals and Linux sockets",
    "summary": "Handshake, states, and how Linux represents connections as inodes/sockets.",
    "difficulty": "Advanced",
    "minutes": 30,
    "level": 12,
    "concepts": 3
  },
  {
    "slug": "namespaces-cgroups",
    "title": "Namespaces, cgroups, and containers",
    "summary": "Containers are processes with isolated namespaces and limited cgroups — not a second kernel.",
    "difficulty": "Advanced",
    "minutes": 34,
    "level": 13,
    "concepts": 3
  },
  {
    "slug": "memory-ipc",
    "title": "Virtual memory and IPC",
    "summary": "Each process has a virtual address space. The kernel maps pages. Processes talk via pipes, sockets, shm, signals.",
    "difficulty": "Advanced",
    "minutes": 32,
    "level": 13,
    "concepts": 3
  },
  {
    "slug": "unix-posix",
    "title": "Unix history, POSIX, BSD, and macOS",
    "summary": "POSIX is the portable contract. BSD and System V are historic Unix branches. macOS is Unix-certified with a BSD userland and a Mach/XNU kernel.",
    "difficulty": "Intermediate",
    "minutes": 30,
    "level": 14,
    "concepts": 3
  },
  {
    "slug": "production-linux",
    "title": "Production Linux and DevOps practice",
    "summary": "Production means change control, observability, backups, least privilege, and reversible deploys.",
    "difficulty": "Advanced",
    "minutes": 30,
    "level": 15,
    "concepts": 3
  }
];

export const catalogLevels: CatalogLevel[] = [
  {
    "id": 0,
    "slug": "fundamentals",
    "title": "Linux Fundamentals",
    "subtitle": "What Linux is, why it exists, and how the pieces fit.",
    "summary": "Operating systems, distributions, kernel vs user space, boot, and the filesystem map.",
    "difficulty": "Beginner",
    "hours": 6,
    "topics": [
      "what-is-linux",
      "linux-vs-unix",
      "distributions",
      "kernel-and-gnu",
      "architecture",
      "boot-and-init",
      "directory-map",
      "help-systems"
    ],
    "prerequisites": []
  },
  {
    "id": 1,
    "slug": "terminal",
    "title": "Terminal & Shell",
    "subtitle": "Speak to the machine through Bash.",
    "summary": "Terminal vs shell, prompts, arguments, PATH, quoting, history, and expansion.",
    "difficulty": "Beginner",
    "hours": 8,
    "topics": [
      "terminal-shell",
      "bash-basics",
      "env-and-path",
      "quoting-expansion"
    ],
    "prerequisites": [
      0
    ]
  },
  {
    "id": 2,
    "slug": "filesystem",
    "title": "Filesystem",
    "subtitle": "Files, inodes, mounts, and the Linux tree.",
    "summary": "Inodes, links, descriptors, mount points, and the FHS directories you will live in.",
    "difficulty": "Beginner",
    "hours": 8,
    "topics": [
      "inodes-and-links",
      "mounts",
      "fhs-deep-dive"
    ],
    "prerequisites": [
      1
    ]
  },
  {
    "id": 3,
    "slug": "permissions",
    "title": "Users & Permissions",
    "subtitle": "Who may do what, and why root is dangerous.",
    "summary": "Users, groups, sudo, mode bits, umask, special bits, and ACLs.",
    "difficulty": "Beginner",
    "hours": 7,
    "topics": [
      "users-groups",
      "mode-bits",
      "special-bits-acl"
    ],
    "prerequisites": [
      2
    ]
  },
  {
    "id": 4,
    "slug": "processes",
    "title": "Processes",
    "subtitle": "Everything running is a process.",
    "summary": "PID, fork/exec, jobs, signals, priorities, zombies, and daemons.",
    "difficulty": "Intermediate",
    "hours": 8,
    "topics": [
      "process-model",
      "jobs-signals",
      "process-control"
    ],
    "prerequisites": [
      1
    ]
  },
  {
    "id": 5,
    "slug": "networking",
    "title": "Networking",
    "subtitle": "From localhost to SSH.",
    "summary": "IP, TCP/UDP, DNS, routing, SSH, and the commands you will use daily.",
    "difficulty": "Intermediate",
    "hours": 10,
    "topics": [
      "net-fundamentals",
      "name-resolution",
      "remote-access"
    ],
    "prerequisites": [
      4
    ]
  },
  {
    "id": 6,
    "slug": "packages",
    "title": "Package Management",
    "subtitle": "Install software the distribution way.",
    "summary": "APT, DNF, Pacman, RPM/DEB, repositories, and dependencies.",
    "difficulty": "Intermediate",
    "hours": 5,
    "topics": [
      "package-managers"
    ],
    "prerequisites": [
      0
    ]
  },
  {
    "id": 7,
    "slug": "bash",
    "title": "Bash Scripting",
    "subtitle": "Turn commands into repeatable tools.",
    "summary": "Variables, control flow, pipes, redirection, functions, and production scripts.",
    "difficulty": "Intermediate",
    "hours": 12,
    "topics": [
      "bash-scripting",
      "pipes-redirection",
      "practical-scripts"
    ],
    "prerequisites": [
      1,
      4
    ]
  },
  {
    "id": 8,
    "slug": "sysadmin",
    "title": "System Administration",
    "subtitle": "Keep a machine running.",
    "summary": "systemd, logs, timers, SSH configuration, hostname, and locale.",
    "difficulty": "Intermediate",
    "hours": 10,
    "topics": [
      "systemd",
      "logs-and-jobs",
      "host-config"
    ],
    "prerequisites": [
      4,
      6
    ]
  },
  {
    "id": 9,
    "slug": "storage",
    "title": "Storage & Filesystems",
    "subtitle": "Disks, partitions, and capacity.",
    "summary": "GPT/MBR, ext4/XFS/Btrfs, LVM, fstab, and capacity tools.",
    "difficulty": "Advanced",
    "hours": 9,
    "topics": [
      "disks-partitions",
      "lvm-and-fstab"
    ],
    "prerequisites": [
      2
    ]
  },
  {
    "id": 10,
    "slug": "security",
    "title": "Security",
    "subtitle": "Least privilege on a real host.",
    "summary": "SSH keys, firewalls, SELinux/AppArmor, audit, and hardening.",
    "difficulty": "Advanced",
    "hours": 9,
    "topics": [
      "linux-security"
    ],
    "prerequisites": [
      3,
      5
    ]
  },
  {
    "id": 11,
    "slug": "performance",
    "title": "Performance & Monitoring",
    "subtitle": "Find the bottleneck before guessing.",
    "summary": "Load average, memory, I/O, caching, swap, and the standard toolkit.",
    "difficulty": "Advanced",
    "hours": 8,
    "topics": [
      "performance-basics"
    ],
    "prerequisites": [
      4
    ]
  },
  {
    "id": 12,
    "slug": "net-internals",
    "title": "Networking Internals",
    "subtitle": "Sockets, the stack, and failure modes.",
    "summary": "TCP handshake, sockets, routing lookups, and packet path on Linux.",
    "difficulty": "Advanced",
    "hours": 8,
    "topics": [
      "tcp-and-sockets"
    ],
    "prerequisites": [
      5
    ]
  },
  {
    "id": 13,
    "slug": "advanced",
    "title": "Advanced Linux",
    "subtitle": "Kernel interfaces used by containers.",
    "summary": "Namespaces, cgroups, capabilities, virtual memory, IPC, epoll.",
    "difficulty": "Advanced",
    "hours": 12,
    "topics": [
      "namespaces-cgroups",
      "memory-ipc"
    ],
    "prerequisites": [
      4,
      11
    ]
  },
  {
    "id": 14,
    "slug": "unix",
    "title": "Unix & POSIX",
    "subtitle": "The family Linux belongs to.",
    "summary": "Unix history, POSIX, BSD vs System V, and how macOS fits.",
    "difficulty": "Intermediate",
    "hours": 6,
    "topics": [
      "unix-posix"
    ],
    "prerequisites": [
      0
    ]
  },
  {
    "id": 15,
    "slug": "production",
    "title": "Production Linux",
    "subtitle": "What production actually looks like.",
    "summary": "DevOps-facing Linux: services, observability, incidents, and change control.",
    "difficulty": "Advanced",
    "hours": 8,
    "topics": [
      "production-linux"
    ],
    "prerequisites": [
      8,
      10,
      11
    ]
  }
];
