// Generated by scripts/content-stats.mjs — do not edit by hand.
// Run `npm run stats` (or any build) to refresh.
export const stats = {
  questions: 1256,
  mcq: 41,
  commands: 128,
  topics: 40,
  concepts: 122,
  levels: 16,
  challenges: 30,
  labs: 9,
  cheatSheets: 11,
} as const;
